#!/bin/bash

SINK=$( pactl list short | grep RUNNING | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' )
SINK_LINE=$( pactl list sinks | grep 'Sink' | awk  '{print $2 " " NR}' | cut -b 2-6 | awk -v sink=$SINK '{if($1==sink) print $2}' )
MUTE=$( pactl list sinks | grep Mute | awk -v x=$SINK_LINE '{if(NR==x) print $2}')

case $BLOCK_BUTTON in
  3) pactl set-sink-mute $SINK toggle ;;  # right click, mute/unmute
  4) pactl set-sink-volume $SINK +2% ;; # scroll up, increase
  5) pactl set-sink-volume $SINK -2% ;; # scroll down, decrease
esac

if [[ $MUTE == "no" ]]; then
	pactl list sinks | grep Volume | awk -v x=$SINK_LINE '{if(NR==2*(x-1)+1) print $5}'
else
  echo MUTE
fi
